### PR TITLE
Add django

### PR DESCRIPTION
**Pull request by robinandeer**
Add very basic Django setup

I've deployed it on AWS: http://django.z6imvg86qy.eu-central-1.elasticbeanstalk.com/variants/

I'll try to get the automatic deployment working so that every push that passes Travis will re-deploy the app

Now it uses a MySQL database as backend

### CODE REVIEW

**Comment by robinandeer** [comment]
It even has a Travis badge ^^

**Comment by robinandeer** [comment]
I will merge this bc I want to test the CD 😜

**Comment by moonso** [comment]
Do it!

**Comment by moonso** [comment]
Nice work!

**Comment by robinandeer** [comment]
So now I've made it work - so remember that every push anyone of use makes to master will re-deploy the app with the new changes!

**Comment by moonso** [comment]
Cool, what do you mean by re-deploy? Where is it redeployed?

**Comment by robinandeer** [comment]
Same URL: http://django.z6imvg86qy.eu-central-1.elasticbeanstalk.com/variants/

On Amazon. If it passes travis tests it will take the new code and update the instance on the server

**Comment by moonso** [comment]
That's amazing

**Pull request merged**
